frontend/ally/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('', views.about_view, name='about'),
]

frontend/ally/ally/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('home.urls')),
    path('accounts/', include('authentication.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('quiz/', include('focoquiz.urls')),
    path('about/', include('about.urls')),
    path('recipes/', include('recipes.urls')),
)

frontend/ally/focoquiz/urls.py
from django.urls import path
from . import views

app_name = 'focoquiz'

urlpatterns = [
    path('', views.quiz_view, name='quiz'),
]

frontend/ally/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

frontend/ally/recipes/urls.py
# recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'  # Defines the namespace

urlpatterns = [
    path('', views.recipe_list, name='recipe_list'),  # No 'recipes/' prefix
    path('new/', views.recipe_new, name='recipe_new'),  # No 'recipes/' prefix
    path('<int:recipe_id>/', views.recipe_detail, name='recipe_detail'),  # No 'recipes/' prefix
    path('<int:recipe_id>/edit/', views.recipe_edit, name='recipe_edit'),  # No 'recipes/' prefix
    path('<int:recipe_id>/delete/', views.recipe_delete, name='recipe_delete'),  # No 'recipes/' prefix
    path('ingredients/autocomplete/', views.ingredient_autocomplete, name='ingredient_autocomplete'),  # No 'recipes/' prefix
    path('debug-formset/', views.debug_formset_view, name='debug_formset'),
]

frontend/ally/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>{% translate "A L L Y" %}</title>
</head>
<body>
    <header>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <div class="header-content">
            <div class="hamburger-menu">
                <input id="menu__toggle" type="checkbox" />
                <label class="menu__btn" for="menu__toggle">
                    <span></span>
                </label>
                <div class="menu__box">
                    <ul>
                        <li><a href="#" class="menu__item">{% translate "Shop" %}</a></li>
                        <li><a href="{% url 'focoquiz:quiz' %}" class="menu__item">{% translate "Quiz" %}</a></li>
                        <li><a href="{% url 'recipes:recipe_list' %}" class="menu__item">{% translate "Recipes" %}</a></li>
                        <li><a href="#" class="menu__item">{% translate "Lessons" %}</a></li>
                        <li><a href="#" class="menu__item">{% translate "Support material" %}</a></li>
                        <li><a href="{% url 'about:about' %}" class="menu__item">{% translate "About" %}</a></li>
                        {% if user.is_authenticated %}
                            {% with administrator_group='Administrator' %}
                                {% if administrator_group in user.groups.all|stringformat:"s" %}
                                    <li><a href="{% url 'admin:index' %}" class="menu__item">{% translate "Users" %}</a></li>
                                {% endif %}
                            {% endwith %}
                        {% endif %}
                    </ul>
                </div>
            </div>
            <div class="logo-container">
                <a href="{% url 'home:home' %}"><img src="{% static 'img/ally_logo.png' %}" alt="ALLY Logo" class="logo"></a>
                <span class="brand-text">
                    <span class="ally">A L L Y</span>
                </span>
            </div>
            
            <div class="header-actions">
                <div class="active-language-display">
                    <img src="{% static 'img/flags/' %}{{ LANGUAGE_CODE }}.svg" alt="{{ LANGUAGE_CODE }} Flag" class="flag-icon active-language-flag">
                    <div class="language-picker">
                        <ul>
                            {% for language in languages %}
                            <li>
                                <a href="/{{ language.code }}/" class="language-link {% if language.code == LANGUAGE_CODE %}active{% endif %}" hreflang="{{ language.code }}">
                                    <img src="{% static 'img/flags/' %}{{ language.code }}.svg" alt="{{ language.name_local }} Flag" class="flag-icon">
                                    <span class="language-name">{{ language.name_local }}</span>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="auth-section">
                    {% if user.is_authenticated %}
                        <div class="user-dropdown">
                            <div class="user-avatar">
                                {{ user.email|first|upper }}
                            </div>
                            <div class="user-dropdown-content">
                                {% if user.is_staff %}
                                    <a href="{% url 'admin:index' %}">{% translate "Admin" %}</a>
                                {% endif %}
                                <a href="{% url 'authentication:profile' %}">{% translate "Settings" %}</a>
                                <form method="post" action="{% url 'authentication:logout' %}">
                                    {% csrf_token %}
                                    <button type="submit" class="logout-link">{% translate "Logout" %}</button>
                                </form>                                
                            </div>
                        </div>
                    {% else %}
                        <a href="{% url 'authentication:login' %}" class="login-icon-link">
                            <i class="fas fa-user login-icon"></i>
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <p>© 2025 A L L Y. All rights reserved.</p>
    </footer>
    <script src="{% static 'js/script.js' %}"></script>
    {% block extra_js %}  {# This is the important part! #}
    {% endblock %}
</body>
</html>

frontend/ally/templates/base_mitLP.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>ConsciousFit</title>
</head>
<body>
    <header>
        <div class="header-content">
            <div class="logo-container">
                <a href="/"><img src="{% static 'img/ally_logo.png' %}" alt="Ally Logo" class="logo"></a>
                                <span class="brand-text">
                    <span class="consciencia">Consciencia</span>
                    <span class="fitness">Fitness</span>
                </span>
            </div>
            <nav>
                <a href="#">Home</a>
                <a href="#">About</a>
                <a href="#">Services</a>
                <a href="#">Contact</a>
            </nav> 
            <div class="active-language-display">
                <img src="{% static 'img/flags/' %}{{ LANGUAGE_CODE }}.svg" alt="{{ LANGUAGE_CODE }} Flag" class="flag-icon active-language-flag">
            </div>
            <div class="language-picker">
                {% for language in languages %}
                <a href="/{{ language.code }}/" class="language-link {% if language.code == LANGUAGE_CODE %}active{% endif %}" hreflang="{{ language.code }}">
                    <img src="{% static 'img/flags/' %}{{ language.code }}.svg" alt="{{ language.name_local }} Flag" class="flag-icon">
                    <span class="language-name">{{ language.name_local }}</span>
                </a>
                {% endfor %}
            </div>
        </div>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <p>&copy; 2024 ConsciousFit</p>
    </footer>
</body>
</html>